# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 04 Sep 2021 19:55:29 +0000
*               @ALL          0
*               @user         8