# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 04 Sep 2021 21:11:06 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

# user admin password c0nv3rg3nce37
admin:$2y$10$SnnI9kDh8ixXlJ0aE68nMe1R6n5J9CSVB/Z/3wcdPEfJk8psZ/rcy:admin:admin@example.org:admin,user
